-- MySQL Script generated by MySQL Workbench
-- Sat Sep 28 18:31:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema backup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema backup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `backup` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `backup` ;

-- -----------------------------------------------------
-- Table `backup`.`dim_agente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`dim_agente` (
  `AgenteID` INT NOT NULL,
  `Nome` VARCHAR(255) NULL DEFAULT NULL,
  `CPF` VARCHAR(20) NULL DEFAULT NULL,
  `Data_Contratacao` DATE NULL DEFAULT NULL,
  `Departamento` VARCHAR(100) NULL DEFAULT NULL,
  `Turno` VARCHAR(50) NULL DEFAULT NULL,
  `Supervisor` VARCHAR(255) NULL DEFAULT NULL,
  `Telefone` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Data_Criacao` DATETIME NULL DEFAULT NULL,
  `Data_Alteracao` DATETIME NULL DEFAULT NULL,
  `Usuario_Criacao` VARCHAR(255) NULL DEFAULT NULL,
  `Usuario_Alteracao` VARCHAR(255) NULL DEFAULT NULL,
  `Ativo` CHAR(1) NULL DEFAULT NULL,
  `Data_Inicio_Vigente` DATETIME NULL DEFAULT NULL,
  `Data_Fim_Vigente` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`AgenteID`),
  INDEX `idx_data_criacao` (`Data_Criacao` ASC) VISIBLE,
  INDEX `idx_data_alteracao` (`Data_Alteracao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backup`.`dim_canal_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`dim_canal_atendimento` (
  `CanalID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Canal` VARCHAR(255) NULL DEFAULT NULL,
  `Plataforma` VARCHAR(255) NULL DEFAULT NULL,
  `Data_Criacao` DATETIME NULL DEFAULT NULL,
  `Data_Alteracao` DATETIME NULL DEFAULT NULL,
  `Usuario_Criacao` VARCHAR(255) NULL DEFAULT NULL,
  `Usuario_Alteracao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`CanalID`),
  INDEX `idx_data_criacao` (`Data_Criacao` ASC) VISIBLE,
  INDEX `idx_data_alteracao` (`Data_Alteracao` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backup`.`dim_categoria_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`dim_categoria_atendimento` (
  `CategoriaID` INT NOT NULL,
  `Nome_Categoria` VARCHAR(255) NULL DEFAULT NULL,
  `Prioridade` VARCHAR(255) NULL DEFAULT NULL,
  `Data_Criacao` DATETIME NULL DEFAULT NULL,
  `Data_Alteracao` DATETIME NULL DEFAULT NULL,
  `Usuario_Criacao` VARCHAR(255) NULL DEFAULT NULL,
  `Usuario_Alteracao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`CategoriaID`),
  INDEX `idx_data_criacao` (`Data_Criacao` ASC) VISIBLE,
  INDEX `idx_data_alteracao` (`Data_Alteracao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backup`.`dim_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`dim_cliente` (
  `ClienteID` INT NOT NULL,
  `Nome` VARCHAR(255) NULL DEFAULT NULL,
  `CPF_CNPJ` VARCHAR(20) NULL DEFAULT NULL,
  `DataNascimento` DATE NULL DEFAULT NULL,
  `Sexo` VARCHAR(10) NULL DEFAULT NULL,
  `Endereco` VARCHAR(255) NULL DEFAULT NULL,
  `Estado` VARCHAR(50) NULL DEFAULT NULL,
  `Cidade` VARCHAR(50) NULL DEFAULT NULL,
  `Telefone` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Data_Criacao` DATETIME NULL DEFAULT NULL,
  `Data_Alteracao` DATETIME NULL DEFAULT NULL,
  `Usuario_Criacao` VARCHAR(255) NULL DEFAULT NULL,
  `Usuario_Alteracao` VARCHAR(255) NULL DEFAULT NULL,
  `Ativo` CHAR(1) NULL DEFAULT NULL,
  `Data_Inicio_Vigente` DATETIME NULL DEFAULT NULL,
  `Data_Fim_Vigente` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ClienteID`),
  INDEX `idx_data_criacao` (`Data_Criacao` ASC) VISIBLE,
  INDEX `idx_data_alteracao` (`Data_Alteracao` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backup`.`dim_tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`dim_tempo` (
  `TempoID` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL DEFAULT NULL,
  `Dia_Semana` VARCHAR(10) NULL DEFAULT NULL,
  `Dia` INT NULL DEFAULT NULL,
  `Mes` VARCHAR(10) NULL DEFAULT NULL,
  `Numero_Mes` INT NULL DEFAULT NULL,
  `Ano` INT NULL DEFAULT NULL,
  `Bimestre` INT NULL DEFAULT NULL,
  `Trimestre` INT NULL DEFAULT NULL,
  `Semestre` INT NULL DEFAULT NULL,
  PRIMARY KEY (`TempoID`),
  INDEX `idx_data` (`Data` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `backup`.`fato_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `backup`.`fato_atendimento` (
  `AtendimentoID` INT NOT NULL,
  `ClienteID` INT NULL DEFAULT NULL,
  `AgenteID` INT NULL DEFAULT NULL,
  `TempoID` INT NULL DEFAULT NULL,
  `CanalID` INT NULL DEFAULT NULL,
  `CategoriaID` INT NULL DEFAULT NULL,
  `Nivel_Satisfacao` FLOAT NULL DEFAULT NULL,
  `Resolvido` CHAR(1) NULL DEFAULT NULL,
  `Tempo_Espera` FLOAT NULL DEFAULT NULL,
  `Numero_Chamadas` INT NULL DEFAULT NULL,
  `Primeiro_Atendimento` CHAR(1) NULL DEFAULT NULL,
  `Data_Criacao` DATETIME NULL DEFAULT NULL,
  `Data_Alteracao` DATETIME NULL DEFAULT NULL,
  `Usuario_Criacao` VARCHAR(255) NULL DEFAULT NULL,
  `Usuario_Alteracao` VARCHAR(255) NULL DEFAULT NULL,
  `DuracaoAtendimento` INT NULL DEFAULT NULL,
  PRIMARY KEY (`AtendimentoID`),
  INDEX `idx_cliente` (`ClienteID` ASC) VISIBLE,
  INDEX `idx_agente` (`AgenteID` ASC) VISIBLE,
  INDEX `idx_tempo` (`TempoID` ASC) VISIBLE,
  INDEX `idx_canal` (`CanalID` ASC) VISIBLE,
  INDEX `idx_nivel_satisfacao` (`Nivel_Satisfacao` ASC) VISIBLE,
  INDEX `idx_resolvido` (`Resolvido` ASC) VISIBLE,
  INDEX `idx_data_criacao` (`Data_Criacao` ASC) VISIBLE,
  INDEX `idx_data_alteracao` (`Data_Alteracao` ASC) VISIBLE,
  CONSTRAINT `fato_atendimento_ibfk_5`
    FOREIGN KEY (`CategoriaID`)
    REFERENCES `backup`.`dim_categoria_atendimento` (`CategoriaID`),
  CONSTRAINT `fk_agente`
    FOREIGN KEY (`AgenteID`)
    REFERENCES `backup`.`dim_agente` (`AgenteID`),
  CONSTRAINT `fk_canal`
    FOREIGN KEY (`CanalID`)
    REFERENCES `backup`.`dim_canal_atendimento` (`CanalID`),
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `backup`.`dim_cliente` (`ClienteID`),
  CONSTRAINT `fk_tempo`
    FOREIGN KEY (`TempoID`)
    REFERENCES `backup`.`dim_tempo` (`TempoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
